import { Request, Response } from "express";
import { StudySpace } from "../models/StudySpace";
import {
  generateCourseCurriculum,
  generateModuleContent,
  askStudySpaceTutor,
} from "../services/studySpaceAiService";

export const generateStudySpace = async (req: Request, res: Response) => {
  try {
    const { topic, goal } = req.body;
    const userId = (req as any).user?.id;

    if (!topic || !goal) {
      return res.status(400).json({ message: "Topic and goal are required" });
    }

    const curriculumStr = await generateCourseCurriculum(topic, goal);
    
    if (!curriculumStr) {
      return res.status(500).json({ message: "Failed to generate curriculum from AI" });
    }

    // Try to parse the curriculum json
    let curriculumData;
    try {
      const match = curriculumStr.match(/\{[\s\S]*\}/);
      const jsonStr = match ? match[0] : curriculumStr;
      curriculumData = JSON.parse(jsonStr);
    } catch (e) {
      console.error("Failed to parse AI response:", curriculumStr);
      return res.status(500).json({ message: "Invalid curriculum generated by AI" });
    }

    const newStudySpace = new StudySpace({
      userId,
      topic,
      goal,
      title: curriculumData.title || `${topic} Course`,
      description: curriculumData.description || `A comprehensive guide on ${topic}.`,
      modules: curriculumData.modules.map((m: any, index: number) => ({
        title: m.title,
        order: m.order || index + 1,
        summary: m.summary || "",
        contentGenerated: false,
      })),
    });

    await newStudySpace.save();

    res.status(201).json(newStudySpace);
  } catch (error) {
    console.error("Error generating study space:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const getStudySpaces = async (req: Request, res: Response) => {
  try {
    const userId = (req as any).user?.id;
    const spaces = await StudySpace.find({ userId }).sort({ createdAt: -1 });
    res.status(200).json(spaces);
  } catch (error) {
    console.error("Error fetching study spaces:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const getStudySpaceById = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const userId = (req as any).user?.id;
    
    const space = await StudySpace.findOne({ _id: id, userId });
    if (!space) {
      return res.status(404).json({ message: "Study space not found" });
    }
    
    res.status(200).json(space);
  } catch (error) {
    console.error("Error fetching study space:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const getModuleContent = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const userId = (req as any).user?.id;
    
    const space = await StudySpace.findOne({ _id: id, userId });
    if (!space) {
      return res.status(404).json({ message: "Study space not found" });
    }
    
    const moduleId = req.params.moduleId as string;
    const module = space.modules.id(moduleId);
    if (!module) {
      return res.status(404).json({ message: "Module not found" });
    }
    
    // If already generated, return it
    if (module.contentGenerated) {
      return res.status(200).json(module);
    }
    
    // Generate content lazily
    const contentStr = await generateModuleContent(space.title, space.topic, module.title);
    
    if (!contentStr) {
      return res.status(500).json({ message: "Failed to generate module content" });
    }
    
    let contentData;
    try {
      const match = contentStr.match(/\{[\s\S]*\}/);
      const jsonStr = match ? match[0] : contentStr;
      contentData = JSON.parse(jsonStr);
    } catch (e) {
      console.error("Failed to parse module content:", contentStr);
      return res.status(500).json({ message: "Invalid module content generated by AI" });
    }
    
    // Update module
    module.summary = contentData.summary || module.summary;
    module.detailedNotes = contentData.detailedNotes || "";
    module.keyConcepts = contentData.keyConcepts || [];
    module.flashcards = contentData.flashcards || [];
    module.quizzes = contentData.quizzes || [];
    module.visualTopics = contentData.visualTopics || null;
    module.contentGenerated = true;
    
    await space.save();
    
    res.status(200).json(module);
  } catch (error) {
    console.error("Error generating module content:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const updateModuleProgress = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { completed } = req.body;
    const userId = (req as any).user?.id;
    
    const space = await StudySpace.findOne({ _id: id, userId });
    if (!space) {
      return res.status(404).json({ message: "Study space not found" });
    }
    
    const moduleId = req.params.moduleId as string;
    const module = space.modules.id(moduleId);
    if (!module) {
      return res.status(404).json({ message: "Module not found" });
    }
    
    module.completed = completed;
    
    // Recalculate progress
    const completedCount = space.modules.filter(m => m.completed).length;
    space.progress = Math.round((completedCount / space.modules.length) * 100);
    
    await space.save();
    
    res.status(200).json(space);
  } catch (error) {
    console.error("Error updating module progress:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const deleteStudySpace = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const userId = (req as any).user?.id;
    
    const result = await StudySpace.deleteOne({ _id: id, userId });
    if (result.deletedCount === 0) {
      return res.status(404).json({ message: "Study space not found" });
    }
    
    res.status(200).json({ message: "Study space deleted successfully" });
  } catch (error) {
    console.error("Error deleting study space:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const askTutor = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { question, history } = req.body;
    const userId = (req as any).user?.id;
    
    const space = await StudySpace.findOne({ _id: id, userId });
    if (!space) {
      return res.status(404).json({ message: "Study space not found" });
    }
    
    const moduleId = req.params.moduleId as string; 
    const module = space.modules.id(moduleId);
    if (!module || !module.contentGenerated) {
      return res.status(400).json({ message: "Module content not ready" });
    }
    
    const context = `
    Module Title: ${module.title}
    Summary: ${module.summary}
    Notes: ${module.detailedNotes}
    Key Concepts: ${(module.keyConcepts || []).join(', ')}
    `;
    
    const answer = await askStudySpaceTutor(context, question, history);
    
    res.status(200).json({ answer });
  } catch (error) {
    console.error("Error asking tutor:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
